/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.Arrays;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }
    public int[] findErrorNums(int[] nums) {
        int[] arr = new int[2];
        int n = nums.length;
        for (int i = 0; i < n; i++) {
            int idx = Math.abs(nums[i]) - 1;
            if (nums[idx] < 0) {
                arr[0] = Math.abs(nums[i]);
            } else {
                nums[idx] = -nums[idx];
            }
        }
        for (int i = 0; i < n; i++) {
            if (nums[i] > 0) {
                arr[1] = i + 1;
                break;
            }
        }
        return arr;
    }
    public static void main(String[] args) {
        int[] nums = {3,2,3,4,6,5};
        System.out.println(Arrays.toString(new App().findErrorNums(nums)));
    }
}
